appVersion: ""
hostname: changedetection.ijmacd.com
web:
  replicaCount: 1
  repository:
    image: docker.io/ijmacd/changedetection
  persistence:
    enabled: true
    storage_class: "local-path"
    capacity: "8Gi"
  tls:
    enabled: false
  local:
    enabled: false
theboaterProxy:
  replicaCount: 1
  repository:
    image: docker.io/ijmacd/theboater-proxy
