apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-web'
  labels:
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/version: '{{ .Chart.Version }}'
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      app.kubernetes.io/instance: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web
        app.kubernetes.io/instance: '{{ .Release.Name }}'
    spec:
      containers:
        - name: web
          image: '{{ .Values.web.repository.image }}{{ if ne .Values.appVersion "" }}:{{ .Values.appVersion }}{{ end }}'
          volumeMounts:
            - mountPath: /datastore
              name: web-data
          env:
            - name: BASE_URL
              value: https://{{ .Values.hostname }}
          ports:
            - name: web
              containerPort: 5000
          resources:
            requests:
              memory: 254Mi
              cpu: 10m
            limits:
              memory: 254Mi
      volumes:
        - name: web-data
          {{- if  .Values.web.persistence.enabled }}
          persistentVolumeClaim:
            claimName: '{{ .Release.Name }}-web-data-{{ .Values.web.persistence.storage_class }}'
          {{ else }}
          emptyDir: {}
          {{- end }}